# Generated by Django 4.0.3 on 2022-03-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_rename_url_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
